#!/bin/sh

if [ ! -f /sys/class/gpio/export ]; then
        exit 0
fi

### enable M.2 5G RM500U-CN Module Power ###
echo 443 > /sys/class/gpio/export
echo 431 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio431/direction
echo   0 > /sys/class/gpio/gpio431/value

sleep 30

#/sbin/quectel-CM -f /tmp/q-cm.log
/sbin/quectel-CM 2>&1 | tee -a /tmp/q-cm.log
